<?php
// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/../config/database.php';

// Composer autoload
require_once __DIR__ . '/../vendor/autoload.php';

use Dompdf\Dompdf;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Validate input
$id = $_GET['id'] ?? null;
$type = $_GET['type'] ?? null;
if (!$id || !$type) {
    http_response_code(400);
    echo 'Missing id or type parameter.';
    exit;
}

// Fetch application data
$stmt = $pdo->prepare('SELECT * FROM applications WHERE id = ? LIMIT 1');
$stmt->execute([$id]);
$app = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$app) {
    http_response_code(404);
    echo 'Application not found.';
    exit;
}

$fields = [
    'Disbursed Date' => 'disbursed_date',
    'Channel Code' => 'channel_code',
    'Dealing Person Name' => 'dealing_person_name',
    'Customer Name' => 'customer_name',
    'Mobile Number' => 'mobile_number',
    'RC Number' => 'rc_number',
    'Engine Number' => 'engine_number',
    'Chassis Number' => 'chassis_number',
    'Old HP' => 'old_hp',
    'Existing Lender' => 'existing_lender',
    'Case Type' => 'case_type',
    'Financer Name' => 'financer_name',
    'Loan Amount' => 'loan_amount',
    'Interest Rate' => 'rate_of_interest',
    'Tenure (Months)' => 'tenure_months',
    'RC Collection Method' => 'rc_collection_method',
    'Channel Name' => 'channel_name',
    'PDD Status' => 'pdd_status',
    'Created At' => 'created_at',
];

switch (strtolower($type)) {
    case 'pdf':
        $options = new \Dompdf\Options();
        $options->set('isHtml5ParserEnabled', true);
        $dompdf = new Dompdf($options);
        $logoPath = __DIR__ . '/../assets/logo.png';
        $logoData = '';
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath));
        }
        $html = '<div style="max-width:700px;margin:0 auto;font-family:sans-serif;">';
        $html .= '<div style="text-align:center;margin-bottom:24px;">';
        if ($logoData) {
            $html .= '<img src="' . $logoData . '" alt="Logo" style="height:60px;margin-bottom:10px;"><br>';
        }
        $html .= '<span style="font-size:28px;font-weight:bold;color:#d32f2f;">Finonest</span><br>';
        $html .= '<span style="font-size:16px;color:#888;">Loan Application Details</span>';
        $html .= '</div>';
        // Customer Information
        $html .= '<div style="background:#f5f5f5;padding:12px 18px;border-radius:8px 8px 0 0;border:1px solid #eee;border-bottom:none;">';
        $html .= '<span style="font-size:20px;font-weight:600;color:#d32f2f;">' . htmlspecialchars($app['customer_name']) . '</span>';
        $html .= ' <span style="font-size:13px;color:#888;">(' . htmlspecialchars($app['id']) . ')</span>';
        $html .= '</div>';
        $html .= '<table style="width:100%;border-collapse:collapse;font-size:15px;border:1px solid #eee;margin-bottom:0;">';
        $html .= '<thead>';
        $html .= '<tr>';
        $html .= '<th style="background:#f5f5f5;text-align:left;padding:10px 8px;border:1px solid #e0e0e0;width:32%;font-weight:600;color:#333;">Field</th>';
        $html .= '<th style="background:#f5f5f5;text-align:left;padding:10px 8px;border:1px solid #e0e0e0;font-weight:600;color:#333;">Value</th>';
        $html .= '</tr>';
        $html .= '</thead>';
        $html .= '<tbody>';
        foreach ($fields as $label => $key) {
            $val = $app[$key] ?? '-';
            if ($key === 'old_hp') {
                $val = $val ? 'Yes' : 'No';
            }
            if ($key === 'loan_amount' && is_numeric($val)) {
                $val = '₹' . number_format($val);
            }
            if ($key === 'rate_of_interest' && $val !== '-') {
                $val = $val . '%';
            }
            if ($key === 'tenure_months' && $val !== '-') {
                $val = $val . ' months';
            }
            $html .= '<tr>';
            $html .= '<td style="padding:10px 8px;border:1px solid #e0e0e0;background:#fafafa;font-weight:500;color:#333;">' . htmlspecialchars($label) . '</td>';
            $html .= '<td style="padding:10px 8px;border:1px solid #e0e0e0;">' . htmlspecialchars($val) . '</td>';
            $html .= '</tr>';
        }
        $html .= '</tbody></table>';
        $html .= '<div style="margin-top:30px;text-align:center;color:#aaa;font-size:13px;">Generated by Finonest &copy; ' . date('Y') . '</div>';
        $html .= '</div>';
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        $filename = 'application_' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $app['customer_name'] ?? $id) . '.pdf';
        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        echo $dompdf->output();
        exit;
    case 'xlsx':
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $col = 'A';
        foreach (array_keys($fields) as $header) {
            $sheet->setCellValue($col.'1', $header);
            $col++;
        }
        $row = 2;
        $col = 'A';
        foreach ($fields as $key) {
            $sheet->setCellValue($col.$row, $app[$key] ?? '-');
            $col++;
        }
        // Branding row at the bottom
        $sheet->setCellValue('A' . ($row + 2), 'Generated by Finonest');
        $writer = new Xlsx($spreadsheet);
        $filename = 'application_' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $app['customer_name'] ?? $id) . '.xlsx';
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        $writer->save('php://output');
        exit;
    case 'csv':
        header('Content-Type: text/csv');
        $filename = 'application_' . preg_replace('/[^a-zA-Z0-9_-]/', '_', $app['customer_name'] ?? $id) . '.csv';
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        $out = fopen('php://output', 'w');
        fputcsv($out, array_keys($fields));
        $row = [];
        foreach ($fields as $key) {
            $row[] = $app[$key] ?? '-';
        }
        fputcsv($out, $row);
        fputcsv($out, []);
        fputcsv($out, ['Generated by Finonest']);
        fclose($out);
        exit;
    default:
        http_response_code(400);
        echo 'Invalid export type.';
        exit;
}
